Get the gene names for the drugs in the Colleens_selleck_chem_results_partial_8-28-20v4 from the known interactions

In [1]:
import pandas as pd

In [14]:
colleen_df = pd.read_csv("data/colleen_selleck_chem_results_partial_8-28-20v4.csv")
colleen_df = pd.DataFrame.drop_duplicates(colleen_df)
colleen_df.head()

           Drug                                          DC.SMILES
0   palbociclib  CC(=O)C1=C(C)C2=C(N=C(NC3=NC=C(C=C3)N3CCNCC3)N...
1   gemcitabine  NC1=NC(=O)N(C=C1)[C@@H]1O[C@H](CO)[C@@H](O)C1(F)F
3  Oxibendazole                  CCCOC1=CC2=C(C=C1)N=C(N2)NC(=O)OC
4   solifenacin  O=C(O[C@H]1CN2CCC1CC2)N1CCC2=CC=CC=C2[C@@H]1C1...
5   miltefosine         CCCCCCCCCCCCCCCCOP([O-])(=O)OCC[N+](C)(C)C

In [18]:
known_interactions_df = pd.read_csv("data/interactions.csv", usecols=[1, 2])
known_interactions_df = pd.DataFrame.drop_duplicates(known_interactions_df)
known_interactions_df.drug = known_interactions_df.drug.apply(lambda x: x.lower())
known_interactions_df.head()

      gene              drug
0  SLC12A1  methyclothiazide
1     TUBB       ixabepilone
2   ADRA1B         indoramin
3   ADRA2A       brimonidine
4    PDE4D        difamilast

In [20]:
merge_df = pd.merge(colleen_df, known_interactions_df, left_on='Drug', right_on='drug', how='inner')
merge_df.head()

,Drug,DC.SMILES,gene,drug
0,palbociclib,CC(=O)C1=C(C)C2=C(N=C(NC3=NC=C(C=C3)N3CCNCC3)N...,ESR1,palbociclib
1,palbociclib,CC(=O)C1=C(C)C2=C(N=C(NC3=NC=C(C=C3)N3CCNCC3)N...,MAP4K5,palbociclib
2,palbociclib,CC(=O)C1=C(C)C2=C(N=C(NC3=NC=C(C=C3)N3CCNCC3)N...,CDK6,palbociclib
3,palbociclib,CC(=O)C1=C(C)C2=C(N=C(NC3=NC=C(C=C3)N3CCNCC3)N...,FLT3,palbociclib
4,palbociclib,CC(=O)C1=C(C)C2=C(N=C(NC3=NC=C(C=C3)N3CCNCC3)N...,ERBB2,palbociclib

In [33]:
merge_df.drug.unique()

array(['palbociclib', 'gemcitabine', 'solifenacin', 'miltefosine',
       'caspofungin', 'quinidine', 'masoprocol', 'sertraline',
       'dexlansoprazole', 'clofazimine', 'chloroquine', 'benzydamine',
       'nicardipine', 'amoxapine', 'luliconazole', 'ebastine',
       'vinorelbine', 'nelfinavir', 'cyclobenzaprine', 'micafungin',
       'procyclidine', 'terfenadine', 'pimozide', 'proadifen',
       'mefloquine', 'hydroxychloroquine', 'vinblastine', 'fluphenazine',
       'hydroquinone', 'amodiaquine', 'lercanidipine', 'dextromethorphan',
       'chlorotrianisene', 'prochlorperazine', 'hexachlorophene',
       'desogestrel', 'efavirenz', 'cinnarizine', 'perphenazine',
       'dalbavancin', 'perospirone', 'propiverine', 'terconazole',
       'melitracen', 'nilotinib', 'arformoterol', 'paroxetine',
       'piperaquine', 'cyclofenil', 'chlorprothixene', 'dasabuvir',
       'promazine', 'vortioxetine', 'ethacrynic acid', 'thioridazine',
       'triflupromazine', 'carvedilol', 'atorvastatin', 'abemaciclib',
       'nebivolol', 'chlorpromazine', 'raloxifene', 'doxazosin',
       'dronedarone', 'cabergoline', 'garenoxacin', 'pitolisant',
       'fingolimod', 'osimertinib', 'crizotinib', 'sunitinib',
       'cobimetinib', 'pimavanserin', 'olmutinib', 'thiothixene',
       'penbutolol'], dtype=object)

In [24]:
merge_df.describe()

,Drug,DC.SMILES,gene,drug
count,1143,1143,1143,1143
unique,76,76,520,76
top,gemcitabine,NC1=NC(=O)N(C=C1)[C@@H]1O[C@H](CO)[C@@H](O)C1(F)F,CYP2D6,gemcitabine
freq,82,82,26,82

In [25]:
gordon_df = pd.read_csv("data/Gordon_Nature_DrugTargets_April2020.csv")
gordon_df.head()

,Bait,Preys,PreyGene,MIST,Saint_BFDR,AvgSpec,Spec,CtrlCounts,FoldChange,SaintScore,TDL
0,SARS-CoV2 E,P05023,ATP1A1,0.330669,0.00,8.67,8|9|9,0|0|0|0|0|0|0|0|1|0|0,86.67,1.00,Tclin
1,SARS-CoV2 E,Q9BQB6,VKORC1,0.370303,0.69,1.00,1|1|1,0|0|0|0|0|0|0|0|0|0|0,10.00,0.00,Tclin
2,SARS-CoV2 E,Q9BUF5,TUBB6,0.279343,0.08,1.67,2|1|2,0|0|0|0|0|0|0|0|0|0|0,16.67,0.64,Tclin
3,SARS-CoV2 M,O14980,XPO1,0.552725,0.00,23.67,27|20|24,0|0|0|0|0|0|0|0|0|0|0,236.67,1.00,Tclin
4,SARS-CoV2 M,O75306,NDUFS2,0.455361,0.00,6.00,7|6|5,0|0|0|0|0|0|0|0|0|0|0,60.00,1.00,Tclin

In [31]:
len(gordon_df.PreyGene.unique())

68

In [27]:
merge_all_df = pd.merge(merge_df, gordon_df, left_on='gene', right_on='PreyGene', how='inner')
merge_all_df.head()

,Drug,DC.SMILES,gene,drug,Bait,Preys,PreyGene,MIST,Saint_BFDR,AvgSpec,Spec,CtrlCounts,FoldChange,SaintScore,TDL
0,gemcitabine,NC1=NC(=O)N(C=C1)[C@@H]1O[C@H](CO)[C@@H](O)C1(F)F,SLC29A1,gemcitabine,SARS-CoV2 M,Q99808,SLC29A1,0.744657,0.69,1.00,1|1|1,0|0|0|0|0|0|0|0|0|0|0,10.00,0.00,Tclin
1,sertraline,CN[C@H]1CC[C@@H](C2=CC(Cl)=C(Cl)C=C2)C2=CC=CC=C12,COMT,sertraline,SARS-CoV2 nsp7,P21964,COMT,0.745232,0.04,2.00,0|3|3,0|0|0|0|0|0|0|0|0|0|0,20.00,0.66,Tclin
2,paroxetine,FC1=CC=C(C=C1)[C@@H]1CCNC[C@H]1COC1=CC2=C(OCO2...,COMT,paroxetine,SARS-CoV2 nsp7,P21964,COMT,0.745232,0.04,2.00,0|3|3,0|0|0|0|0|0|0|0|0|0|0,20.00,0.66,Tclin
3,vinorelbine,CCC1=C[C@@H]2C[N@](C1)CC1=C(NC3=C1C=CC=C3)[C@@...,TUBB2A,vinorelbine,SARS-CoV2 M,Q13885,TUBB2A,0.360291,0.69,1.00,1|1|1,0|0|0|0|0|0|0|0|0|0|0,10.00,0.00,Tclin
4,vinorelbine,CCC1=C[C@@H]2C[N@](C1)CC1=C(NC3=C1C=CC=C3)[C@@...,TUBB2A,vinorelbine,SARS-CoV2 nsp11,Q13885,TUBB2A,0.406156,0.08,1.67,2|2|1,0|0|0|0|0|0|0|0|0|0|0,16.67,0.64,Tclin

In [29]:
len(merge_all_df)

73

Unique drugs in the merged file

In [34]:
len(merge_all_df.drug.unique())

10

In [32]:
merge_all_df.to_csv("colleen_interactions_and_gordon.csv", index=False)

Find the predicted protein names from the LigandNet predictions using gene/PreyGene names

In [38]:
from glob import glob
import os
prediction_files = glob("predictions/*.csv")

In [47]:
def pred(file):
    drug_name = os.path.split(file)[1][:-4]
    _df = pd.read_csv(file)
    _df['drug'] = pd.Series([drug_name]*len(_df))
    return _df

In [59]:
predictions_df = pd.concat([pred(p) for p in prediction_files], ignore_index=True)
predictions_df.drug = predictions_df.drug.apply(lambda x: x.lower())
predictions_df.head()

,uniprot_id,confidence,protein_name,gene_name,drug
0,O00329,0.79,phosphatidylinositol_4_5_bisphosphate_3_kinase...,PIK3CD,palbociclib
1,O00408,0.79,cgmp_dependent_3_5_cyclic_phosphodiesterase,PDE2A,palbociclib
2,O14757,0.54,serine_threonine_protein_kinase_chk1,CHEK1,palbociclib
3,O14965,0.97,aurora_kinase_a,AURKA,palbociclib
4,O60674,0.99,tyrosine_protein_kinase_jak2,JAK2,palbociclib

In [60]:
len(predictions_df)

2464

In [61]:
gordon_to_predictrions_df = pd.merge(gordon_df, predictions_df, left_on='PreyGene', right_on='gene_name', how='inner')
gordon_to_predictrions_df.head()

,Bait,Preys,PreyGene,MIST,Saint_BFDR,AvgSpec,Spec,CtrlCounts,FoldChange,SaintScore,TDL,uniprot_id,confidence,protein_name,gene_name,drug
0,SARS-CoV2 M,P49721,PSMB2,0.515787,0.08,1.67,2|1|2,0|0|0|0|0|0|0|0|0|0|0,16.67,0.64,Tclin,P49721,0.82,proteasome_subunit_beta_type_2,PSMB2,caspofungin
1,SARS-CoV2 M,P49721,PSMB2,0.515787,0.08,1.67,2|1|2,0|0|0|0|0|0|0|0|0|0|0,16.67,0.64,Tclin,P49721,1.00,proteasome_subunit_beta_type_2,PSMB2,nelfinavir
2,SARS-CoV2 M,P49721,PSMB2,0.515787,0.08,1.67,2|1|2,0|0|0|0|0|0|0|0|0|0|0,16.67,0.64,Tclin,P49721,1.00,proteasome_subunit_beta_type_2,PSMB2,anidulafungin
3,SARS-CoV2 M,P49721,PSMB2,0.515787,0.08,1.67,2|1|2,0|0|0|0|0|0|0|0|0|0|0,16.67,0.64,Tclin,P49721,0.88,proteasome_subunit_beta_type_2,PSMB2,micafungin
4,SARS-CoV2 M,P49721,PSMB2,0.515787,0.08,1.67,2|1|2,0|0|0|0|0|0|0|0|0|0|0,16.67,0.64,Tclin,P49721,1.00,proteasome_subunit_beta_type_2,PSMB2,chlorotrianisene

In [78]:
gordon_to_predictrions_df.to_csv('gordon_to_predictions.csv', index=False)

In [62]:
len(gordon_to_predictrions_df.drug.unique())

17

In [63]:
set(merge_all_df.drug.to_list()).intersection(gordon_to_predictrions_df.drug.to_list())

{'vinblastine', 'vinorelbine'}

In [65]:
import json

In [72]:
uniprot_to_gene = json.load(open("../../uniprot_to_gene.json"))

In [73]:
models = [m.split('.')[0] for m in models]
models_genes = [uniprot_to_gene[m] for m in models]

In [79]:
gordon_in_ligandnet_df = gordon_df[gordon_df.PreyGene.isin(models_genes)]
gordon_in_ligandnet_df.head()

,Bait,Preys,PreyGene,MIST,Saint_BFDR,AvgSpec,Spec,CtrlCounts,FoldChange,SaintScore,TDL
16,SARS-CoV2 M,P14324,FDPS,0.519930,0.69,1.00,1|1|1,0|0|0|0|0|0|0|0|0|0|0,10.00,0.00,Tclin
20,SARS-CoV2 M,P49721,PSMB2,0.515787,0.08,1.67,2|1|2,0|0|0|0|0|0|0|0|0|0|0,16.67,0.64,Tclin
26,SARS-CoV2 M,Q99808,SLC29A1,0.744657,0.69,1.00,1|1|1,0|0|0|0|0|0|0|0|0|0|0,10.00,0.00,Tclin
46,SARS-CoV2 nsp14,P12268,IMPDH2,0.989668,0.00,18.33,23|17|15,0|0|0|0|0|0|0|0|0|0|0,183.33,1.00,Tclin
65,SARS-CoV2 nsp7,P21964,COMT,0.745232,0.04,2.00,0|3|3,0|0|0|0|0|0|0|0|0|0|0,20.00,0.66,Tclin

In [80]:
gordon_in_ligandnet_df.to_csv('gordon_in_ligandnet.csv', index=False)